In [1]:
#PROBABILTY MAKER FOR FUTURE GAMES

import numpy as np  
import pandas as pd 
import io
import requests

In [2]:
url = "http://api.clubelo.com/Fixtures"
s = requests.get(url).content
df = pd.read_csv(io.StringIO(s.decode('utf-8')))

df = df[['Date','Country', 'Home','Away', 'GD<-5','GD=-5','GD=-4','GD=-3','GD=-2','GD=-1','GD=0','GD=1','GD=2','GD=3','GD=4','GD=5','GD>5']]
df['A']= df.iloc[:, -13:-7].sum(axis=1)  
df['H']= df.iloc[:, -7:-1].sum(axis=1)    

df.drop(['GD<-5','GD=-5','GD=-4','GD=-3','GD=-2','GD=-1','GD=1','GD=2','GD=3','GD=4','GD=5','GD>5'], axis=1, inplace=True)
df.rename(columns={'GD=0':'D'}, inplace=True)
df = df[['Date','Country', 'Home','Away', 'H', 'D', 'A']]

In [3]:
df

          Date Country            Home      Away       H       D       A
0   2020-01-11     ENG   Middlesbrough     Derby  0.4426  0.3192  0.2381
1   2020-01-11     ENG         Chelsea   Burnley  0.6607  0.2061  0.1332
2   2020-01-11     ENG         Everton  Brighton  0.5184  0.2791  0.2023
3   2020-01-11     ENG       Brentford       QPR  0.6052  0.2253  0.1694
4   2020-01-11     ENG      Man United   Norwich  0.7197  0.1754  0.1049
..         ...     ...             ...       ...     ...     ...     ...
62  2020-01-15     ESP  Rayo Vallecano      Lugo  0.6012  0.2346  0.1642
63  2020-01-15     ESP          Huesca  Tenerife  0.5734  0.2529  0.1736
64  2020-01-15     FRA           Nimes    Rennes  0.2950  0.2729  0.4320
65  2020-01-15     FRA          Monaco  Paris SG  0.1494  0.1979  0.6527
66  2020-01-15     FRA          Amiens     Reims  0.2867  0.3024  0.4110

[67 rows x 7 columns]

In [7]:
df = df.tail(6)

In [8]:
df

          Date Country      Home        Away       H       D       A
36  2020-01-06     ITA  Atalanta       Parma  0.7204  0.1709  0.1085
37  2020-01-06     ITA  Juventus    Cagliari  0.7952  0.1379  0.0668
38  2020-01-06     ITA   Bologna  Fiorentina  0.4599  0.2881  0.2519
39  2020-01-06     ITA     Milan   Sampdoria  0.5463  0.2670  0.1863
40  2020-01-06     ITA    Napoli       Inter  0.4135  0.3039  0.2825
41  2020-01-06     ITA     Lecce     Udinese  0.3757  0.2878  0.3362

In [9]:
form = pd.read_excel('form.xlsx')

In [11]:
form.drop(['Pos', 'P','Pts', 'F','A','GD'], axis=1, inplace=True)
form

              Team                     Sequence
0            Lazio  Â WÂ  Â WÂ  Â WÂ  Â WÂ  Â WÂ  Â WÂ  Â WÂ
1            Inter  Â WÂ  Â WÂ  Â WÂ  Â WÂ  Â DÂ  Â DÂ  Â WÂ
2             Roma  Â WÂ  Â LÂ  Â WÂ  Â WÂ  Â DÂ  Â WÂ  Â WÂ
3         Juventus  Â WÂ  Â WÂ  Â WÂ  Â DÂ  Â LÂ  Â WÂ  Â WÂ
4            Parma  Â DÂ  Â WÂ  Â DÂ  Â LÂ  Â WÂ  Â WÂ  Â DÂ
5         Cagliari  Â WÂ  Â WÂ  Â DÂ  Â WÂ  Â DÂ  Â LÂ  Â LÂ
6         Atalanta  Â LÂ  Â DÂ  Â LÂ  Â WÂ  Â WÂ  Â LÂ  Â WÂ
7           Torino  Â LÂ  Â WÂ  Â LÂ  Â WÂ  Â WÂ  Â DÂ  Â LÂ
8        Sampdoria  Â WÂ  Â DÂ  Â WÂ  Â LÂ  Â LÂ  Â WÂ  Â LÂ
9          Bologna  Â LÂ  Â LÂ  Â DÂ  Â WÂ  Â LÂ  Â WÂ  Â WÂ
10          Verona  Â WÂ  Â WÂ  Â LÂ  Â WÂ  Â LÂ  Â LÂ  Â DÂ
11        Sassuolo  Â WÂ  Â LÂ  Â DÂ  Â DÂ  Â DÂ  Â WÂ  Â LÂ
12         Udinese  Â WÂ  Â DÂ  Â LÂ  Â LÂ  Â DÂ  Â LÂ  Â WÂ
13           Milan  Â LÂ  Â LÂ  Â DÂ  Â WÂ  Â WÂ  Â DÂ  Â LÂ
14         Brescia  Â LÂ  Â LÂ  Â LÂ  Â WÂ  Â WÂ  Â LÂ  Â DÂ
15          Napoli  Â LÂ  Â DÂ  Â DÂ  Â LÂ  Â DÂ  Â LÂ  Â WÂ
16           Lecce  Â DÂ  Â LÂ  Â DÂ  Â WÂ  Â DÂ  Â LÂ  Â LÂ
17            Spal  Â LÂ  Â DÂ  Â DÂ  Â LÂ  Â LÂ  Â LÂ  Â WÂ
18           Genoa  Â LÂ  Â DÂ  Â DÂ  Â LÂ  Â DÂ  Â LÂ  Â LÂ
19      Fiorentina  Â DÂ  Â LÂ  Â LÂ  Â LÂ  Â LÂ  Â DÂ  Â LÂ
20       Benevento  Â WÂ  Â WÂ  Â WÂ  Â WÂ  Â WÂ  Â WÂ  Â WÂ
21       Pordenone  Â WÂ  Â LÂ  Â WÂ  Â WÂ  Â WÂ  Â LÂ  Â WÂ
22  Virtus Entella  Â LÂ  Â WÂ  Â WÂ  Â WÂ  Â LÂ  Â DÂ  Â WÂ
23     Juve Stabia  Â WÂ  Â LÂ  Â LÂ  Â WÂ  Â WÂ  Â DÂ  Â WÂ
24          Spezia  Â LÂ  Â WÂ  Â DÂ  Â WÂ  Â DÂ  Â DÂ  Â WÂ
25       Frosinone  Â LÂ  Â WÂ  Â WÂ  Â WÂ  Â LÂ  Â LÂ  Â DÂ
26         Crotone  Â LÂ  Â DÂ  Â LÂ  Â LÂ  Â WÂ  Â WÂ  Â WÂ
27          Ascoli  Â WÂ  Â DÂ  Â LÂ  Â WÂ  Â LÂ  Â WÂ  Â LÂ
28       Cremonese  Â WÂ  Â DÂ  Â DÂ  Â LÂ  Â WÂ  Â DÂ  Â LÂ
29      Cittadella  Â DÂ  Â DÂ  Â WÂ  Â LÂ  Â DÂ  Â WÂ  Â LÂ
30     Salernitana  Â LÂ  Â DÂ  Â LÂ  Â WÂ  Â DÂ  Â WÂ  Â LÂ
31         Cosenza  Â LÂ  Â DÂ  Â DÂ  Â LÂ  Â WÂ  Â WÂ  Â LÂ
32         Perugia  Â LÂ  Â WÂ  Â DÂ  Â LÂ  Â WÂ  Â DÂ  Â LÂ
33            Pisa  Â DÂ  Â WÂ  Â LÂ  Â WÂ  Â LÂ  Â LÂ  Â DÂ
34          Chievo  Â WÂ  Â LÂ  Â WÂ  Â LÂ  Â DÂ  Â LÂ  Â DÂ
35         Trapani  Â WÂ  Â WÂ  Â LÂ  Â LÂ  Â DÂ  Â DÂ  Â LÂ
36         Pescara  Â DÂ  Â LÂ  Â DÂ  Â LÂ  Â DÂ  Â WÂ  Â DÂ
37         Venezia  Â DÂ  Â LÂ  Â DÂ  Â DÂ  Â LÂ  Â LÂ  Â WÂ
38          Empoli  Â DÂ  Â LÂ  Â WÂ  Â LÂ  Â DÂ  Â LÂ  Â DÂ
39         Livorno  Â LÂ  Â DÂ  Â LÂ  Â LÂ  Â LÂ  Â LÂ  Â DÂ

In [12]:
form = form.astype(str)

In [14]:
for i, row in df.iterrows():
    for j in range(len(form)):
        if df['Home'][i]==form['Team'][j]:
            df.at[i, 'FormH'] = form['Sequence'][j]
        if df['Away'][i]==form['Team'][j]:
            df.at[i, 'FormA'] = form['Sequence'][j]

In [15]:
df

,Date,Country,Home,Away,H,D,A,FormA,FormH
36,2020-01-06,ITA,Atalanta,Parma,0.7204,0.1709,0.1085,DÂ Â WÂ Â DÂ Â LÂ Â WÂ Â WÂ Â D,LÂ Â DÂ Â LÂ Â WÂ Â WÂ Â LÂ Â W
37,2020-01-06,ITA,Juventus,Cagliari,0.7952,0.1379,0.0668,WÂ Â WÂ Â DÂ Â WÂ Â DÂ Â LÂ Â L,WÂ Â WÂ Â WÂ Â DÂ Â LÂ Â WÂ Â W
38,2020-01-06,ITA,Bologna,Fiorentina,0.4599,0.2881,0.2519,DÂ Â LÂ Â LÂ Â LÂ Â LÂ Â DÂ Â L,LÂ Â LÂ Â DÂ Â WÂ Â LÂ Â WÂ Â W
39,2020-01-06,ITA,Milan,Sampdoria,0.5463,0.2670,0.1863,WÂ Â DÂ Â WÂ Â LÂ Â LÂ Â WÂ Â L,LÂ Â LÂ Â DÂ Â WÂ Â WÂ Â DÂ Â L
40,2020-01-06,ITA,Napoli,Inter,0.4135,0.3039,0.2825,WÂ Â WÂ Â WÂ Â WÂ Â DÂ Â DÂ Â W,LÂ Â DÂ Â DÂ Â LÂ Â DÂ Â LÂ Â W
41,2020-01-06,ITA,Lecce,Udinese,0.3757,0.2878,0.3362,WÂ Â DÂ Â LÂ Â LÂ Â DÂ Â LÂ Â W,DÂ Â LÂ Â DÂ Â WÂ Â DÂ Â LÂ Â L

In [33]:
writer = pd.ExcelWriter('PythonExport.xlsx')
df.to_excel(writer,'Sheet1')
writer.save()